# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Pomegranate
tagline:          'Complex applications without complex structure.'
description:      'Complex applications without complex structure.'
built_by:         'Built by <a href="https://github.com/PaperElectron">@PaperElectron</a>'
url:              http://paperelectron.github.io/Pomegranate/
baseurl:          ''

author:
  name:           'Jim Bulkowski'
  url:            https://github.com/PaperElectron/Pomegranate

paginate:         5

# Custom vars
version:          1.9.1

github:
  repo:           https://github.com/PaperElectron/Pomegranate
