# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Pomegranate
tagline:          'The most flexible web framework in the known universe.'
description:      'The most flexible web framework in the known universe.'
built_by:         'Built by <a href="https://github.com/PaperElectron">@PaperElectron</a>'
url:              http://paperelectron.github.io/Pomegranate/
baseurl:          /Pomegranate

author:
  name:           'Jim Bulkowski'
  url:            https://github.com/PaperElectron/Pomegranate

paginate:         5

# Custom vars
version:          0.3.0

github:
  repo:           https://github.com/PaperElectron/Pomegranate
